version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/api"
    commit-message:
      prefix: "build: "
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/api"
    commit-message:
      prefix: "build: "
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ui"
    commit-message:
      prefix: "build: "
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/ui"
    commit-message:
      prefix: "build: "
    schedule:
      interval: "weekly"
